import {
  LayoutDashboard,
  MessageSquare,
  FileText,
  Receipt,
  Landmark,
  Car,
  Bell,
  UserCircle,
} from 'lucide-react'
import { TutorialStep } from '@/lib/tutorial-steps'

export const CLIENT_TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'client-dashboard',
    title: 'Přehled',
    description: 'Váš hlavní přehled — zde vidíte stav dokumentů, zpráv a důležitých termínů.',
    targetSelector: '[data-tour="client-dashboard"]',
    page: '/client/dashboard',
    placement: 'right',
    icon: LayoutDashboard,
  },
  {
    id: 'client-messages',
    title: 'Zprávy',
    description: 'Komunikujte se svým účetním přímo v aplikaci. Všechny konverzace na jednom místě.',
    targetSelector: '[data-tour="client-messages"]',
    page: '/client/messages',
    placement: 'right',
    icon: MessageSquare,
  },
  {
    id: 'client-documents',
    title: 'Dokumenty',
    description: 'Nahrávejte faktury, účtenky a další doklady. Automaticky se přiřadí k správnému období.',
    targetSelector: '[data-tour="client-documents"]',
    page: '/client/documents',
    placement: 'right',
    icon: FileText,
  },
  {
    id: 'client-invoicing',
    title: 'Fakturace',
    description: 'Vystavujte faktury přímo z aplikace. Sledujte platby a upomínky.',
    targetSelector: '[data-tour="client-invoicing"]',
    page: '/client/invoices',
    placement: 'right',
    icon: Receipt,
  },
  {
    id: 'client-taxes',
    title: 'Daně',
    description: 'Přehled vašich daňových povinností — DPH, daň z příjmu, termíny.',
    targetSelector: '[data-tour="client-taxes"]',
    page: '/client/taxes',
    placement: 'right',
    icon: Landmark,
  },
  {
    id: 'client-travel',
    title: 'Kniha jízd',
    description: 'Evidence služebních cest a jízd. Automatické výpočty cestovních náhrad.',
    targetSelector: '[data-tour="client-travel"]',
    page: '/client/travel',
    placement: 'right',
    icon: Car,
  },
  {
    id: 'client-reminders',
    title: 'Připomínky',
    description: 'Důležité termíny a upozornění — nikdy nezmeškáte daňový termín.',
    targetSelector: '[data-tour="client-reminders"]',
    page: '/client/reminders',
    placement: 'right',
    icon: Bell,
  },
  {
    id: 'client-profile',
    title: 'Profil',
    description: 'Nastavení vašeho účtu, firemních údajů a předvoleb.',
    targetSelector: '[data-tour="client-profile"]',
    page: '/client/account',
    placement: 'right',
    icon: UserCircle,
  },
]
