import {
  LayoutDashboard,
  Users,
  Columns3,
  Plus,
  Receipt,
  Settings,
  MessageCircle,
  Inbox,
  Briefcase,
  ScanLine,
  CalendarCheck,
  Send,
  BookOpen,
  UserPlus,
  TrendingUp,
  BarChart3,
  CreditCard,
  Shield,
} from 'lucide-react'

export type TutorialStep = {
  id: string
  title: string
  description: string
  targetSelector: string
  page: string
  placement: 'top' | 'bottom' | 'left' | 'right'
  icon: typeof LayoutDashboard
}

export const TUTORIAL_STEPS: TutorialStep[] = [
  {
    id: 'nav-dashboard',
    title: 'Dashboard',
    description: 'Toto je váš hlavní přehled. Jednotlivé sekce můžete přetahovat a zapínat nebo vypínat přes ikonu ozubeného kolečka.',
    targetSelector: '[data-tour="nav-dashboard"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: LayoutDashboard,
  },
  {
    id: 'nav-clients',
    title: 'Seznam klientů',
    description: 'Zde najdete všechny vaše klienty. Červený badge ukazuje počet položek, které vyžadují vaši pozornost — chybějící doklady, nepřečtené zprávy apod.',
    targetSelector: '[data-tour="nav-clients"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: Users,
  },
  {
    id: 'nav-komunikace',
    title: 'Komunikace',
    description: 'Centrální přehled zpráv od všech klientů. Badge ukazuje počet nepřečtených zpráv, které čekají na vaši odpověď.',
    targetSelector: '[data-tour="nav-komunikace"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: MessageCircle,
  },
  {
    id: 'nav-inbox',
    title: 'Inbox',
    description: 'GTD Inbox — všechny nové úkoly, podněty a požadavky sem přicházejí. Zpracujte je a roztřiďte do projektů nebo úkolů.',
    targetSelector: '[data-tour="nav-inbox"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: Inbox,
  },
  {
    id: 'nav-work',
    title: 'Práce',
    description: 'Přehled vaší práce — úkoly, projekty a odpracovaný čas. Sledujte co je potřeba udělat a zaznamenávejte odpracované hodiny.',
    targetSelector: '[data-tour="nav-work"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: Briefcase,
  },
  {
    id: 'nav-extraction',
    title: 'Vytěžování dokladů',
    description: 'Automatické zpracování dokladů pomocí AI. Nahrajte fakturu nebo účtenku a systém vytáhne klíčové údaje — dodavatel, částka, datum, IČO.',
    targetSelector: '[data-tour="nav-extraction"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: ScanLine,
  },
  {
    id: 'nav-deadlines',
    title: 'Termíny',
    description: 'Kalendář důležitých termínů — DPH, daňová přiznání, uzávěrky. Systém vás upozorní na blížící se deadliny.',
    targetSelector: '[data-tour="nav-deadlines"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: CalendarCheck,
  },
  {
    id: 'nav-reminders',
    title: 'Připomínky',
    description: 'Odesílání připomínek klientům — chybějící doklady, nezaplacené faktury, potřebné dokumenty.',
    targetSelector: '[data-tour="nav-reminders"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: Send,
  },
  {
    id: 'nav-knowledge-base',
    title: 'Znalostní báze',
    description: 'Sdílená znalostní báze pro celý tým — účetní postupy, šablony, předpisy a interní dokumentace.',
    targetSelector: '[data-tour="nav-knowledge-base"]',
    page: '/accountant/dashboard',
    placement: 'right',
    icon: BookOpen,
  },
  {
    id: 'client-row',
    title: 'Detail klienta',
    description: 'Klikněte na libovolného klienta pro otevření jeho detailu. Najdete tam doklady, soubory, záznam práce, firemní údaje a časovou osu.',
    targetSelector: '[data-tour="client-row"]',
    page: '/accountant/clients',
    placement: 'bottom',
    icon: Users,
  },
  {
    id: 'client-tabs',
    title: 'Navigace v klientovi',
    description: 'Mezi sekcemi klienta přepínáte pomocí těchto záložek — Přehled, Doklady, Soubory, Práce, Firma a Časová osa.',
    targetSelector: '[data-tour="client-tabs"]',
    page: '__client_detail__',
    placement: 'bottom',
    icon: Columns3,
  },
  {
    id: 'quick-add',
    title: 'Rychlé přidání úkolu',
    description: 'Tímto tlačítkem rychle vytvoříte nový úkol do Inboxu. Funguje odkudkoli v aplikaci. Klávesová zkratka: Ctrl+N.',
    targetSelector: '[data-tour="quick-add"]',
    page: '__any__',
    placement: 'top',
    icon: Plus,
  },
  {
    id: 'nav-invoicing',
    title: 'Fakturace',
    description: 'Vystavujte faktury klientům s automatickým QR kódem pro platbu. Faktury se generují z odpracovaných hodin a nastavených sazeb.',
    targetSelector: '[data-tour="nav-invoicing"]',
    page: '__any__',
    placement: 'right',
    icon: Receipt,
  },
  {
    id: 'nav-settings',
    title: 'Nastavení',
    description: 'Nastavte si firemní údaje, bankovní spojení, hodinové sazby a další předvolby pro celou aplikaci.',
    targetSelector: '[data-tour="nav-settings"]',
    page: '__any__',
    placement: 'right',
    icon: Settings,
  },
]
