#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env.claimbuddy.local"

echo "== ClaimBuddy local Supabase bootstrap =="
echo "Project: $ROOT_DIR"

supabase start --workdir "$ROOT_DIR"

STATUS_ENV="$(supabase status -o env --workdir "$ROOT_DIR")"
if [[ -z "$STATUS_ENV" ]]; then
  echo "Supabase status returned no env output" >&2
  exit 1
fi

eval "$STATUS_ENV"

if [[ -z "${DB_URL:-}" || -z "${API_URL:-}" || -z "${ANON_KEY:-}" || -z "${SERVICE_ROLE_KEY:-}" ]]; then
  echo "Missing required local Supabase status variables" >&2
  exit 1
fi

psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$ROOT_DIR/supabase/claimbuddy.bootstrap.sql"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/bootstrap-claimbuddy-local-supabase.sh
NEXT_PUBLIC_CLAIMS_SUPABASE_URL=$API_URL
NEXT_PUBLIC_CLAIMS_SUPABASE_ANON_KEY=$ANON_KEY
CLAIMS_SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
NEXT_PUBLIC_APP_URL=http://127.0.0.1:3020
EOF

echo ""
echo "Local ClaimBuddy Supabase is ready."
echo "Env written to: $ENV_FILE"
echo ""
echo "To run ClaimBuddy against the local claims DB:"
echo "  set -a"
echo "  source /root/Projects/UcetniWebApp/.env.local"
echo "  source $ENV_FILE"
echo "  set +a"
echo "  npm run start -- -H 127.0.0.1 -p 3020"
